apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-backend
  template:
    metadata:
      labels:
        app: sample-backend
    spec:
      initContainers:
      - name: write-hostname
        image: busybox:latest
        command: ['sh', '-c', 'echo $NODE_NAME > /var/www/hostname']
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: hostname-volume
          mountPath: /var/www
      containers:
      - name: sample-backend
        image: ghcr.io/mattuu0-test-env/k8s-sample-app/app-hostname:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: sample-app-secret
                key: DATABASE_URL
        volumeMounts:
        - name: hostname-volume
          mountPath: /var/www
      volumes:
      - name: hostname-volume
        emptyDir: {}
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 10
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 10
