apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secret
  namespace: sample-app
type: Opaque
data:
  # sample-app:mLbOiz7ZdYwHYifAOnMVBJQfnWMntXqEqTqG8GDEBuS0dLGBzJEWnaa5ua4u2ZwX@tcp(cluster1-haproxy.pxc:3306)/sample_app_main?charset=utf8mb4&parseTime=True&loc=Local
  DATABASE_URL: "c2FtcGxlLWFwcDptTGJPaXo3WmRZd0hZaWZBT25NVkJKUWZuV01udFhxRXFUcUc4R0RFQnVTMGRMR0J6SkVXbmFhNXVhNHUyWndYQHRjcChjbHVzdGVyMS1oYXByb3h5LnB4YzozMzA2KS9zYW1wbGVfYXBwX21haW4/Y2hhcnNldD11dGY4bWI0JnBhcnNlVGltZT1UcnVlJmxvYz1Mb2NhbA=="
